### ISSUE TITLE
[IQ] - What's New in Angular 7 ?

### ISSUE THREAD

**Issue by SonalMane254** [CodeKul/wk-1030to1200-angular#8]

**Comment by aniruddhha** [comment]
Kindly check following this [blog](https://blog.angular.io/version-7-of-angular-cli-prompts-virtual-scroll-drag-and-drop-and-more-c594e22e7b8c) for detailed features of angular 7 and [changelog](https://github.com/angular/angular/blob/master/CHANGELOG.md) for changes
